#!/usr/bin/env bash
set -euo pipefail

# Export deployed contract addresses from a Forge deployment JSON
# to a TypeScript module the frontend can import.
#
# Usage: ./scripts/export-addresses.sh [network]
#   network defaults to "sepolia"

NETWORK="${1:-sepolia}"
DEPLOY_JSON="contracts/deployments/${NETWORK}.json"
FRONTEND_DIR="frontend/src/lib/contracts"
OUTPUT="$FRONTEND_DIR/addresses.ts"

if [ ! -f "$DEPLOY_JSON" ]; then
  echo "error: $DEPLOY_JSON not found — run the deploy script first"
  exit 1
fi

mkdir -p "$FRONTEND_DIR"

entryPoint=$(jq -r '.entryPoint' "$DEPLOY_JSON")
factory=$(jq -r '.factory' "$DEPLOY_JSON")
accountImpl=$(jq -r '.accountImplementation' "$DEPLOY_JSON")
counter=$(jq -r '.counter' "$DEPLOY_JSON")
faucetToken=$(jq -r '.faucetToken' "$DEPLOY_JSON")

cat > "$OUTPUT" <<EOF
// Auto-generated by scripts/export-addresses.sh — do not edit manually.
// Network: ${NETWORK}

export const addresses = {
  entryPoint: '${entryPoint}',
  factory: '${factory}',
  accountImplementation: '${accountImpl}',
  counter: '${counter}',
  faucetToken: '${faucetToken}',
} as const;
EOF

echo "done: addresses written to $OUTPUT (network: $NETWORK)"
