#!/usr/bin/env bash
set -euo pipefail

# Export deployed contract addresses from a Forge deployment JSON
# to a TypeScript module the frontend can import.
#
# Usage: ./scripts/export-addresses.sh [chain_id]
#   chain_id defaults to 11155111 (Sepolia)

CHAIN_ID="${1:-11155111}"
DEPLOY_JSON="contracts/deployments/${CHAIN_ID}.json"
FRONTEND_DIR="frontend/src/lib/contracts"
OUTPUT="$FRONTEND_DIR/addresses.ts"

if [ ! -f "$DEPLOY_JSON" ]; then
  echo "error: $DEPLOY_JSON not found — run the deploy script first"
  exit 1
fi

mkdir -p "$FRONTEND_DIR"

read_addr() {
  local val
  val=$(jq -er ".$1" "$DEPLOY_JSON") || { echo "error: key '$1' missing or null in $DEPLOY_JSON"; exit 1; }
  printf '%s' "$val"
}

entryPoint=$(read_addr entryPoint)
factory=$(read_addr factory)
accountImpl=$(read_addr accountImplementation)
counter=$(read_addr counter)
faucetToken=$(read_addr faucetToken)

cat > "$OUTPUT" <<EOF
// Auto-generated by scripts/export-addresses.sh — do not edit manually.
// Chain ID: ${CHAIN_ID}

export const addresses = {
  entryPoint: '${entryPoint}',
  factory: '${factory}',
  accountImplementation: '${accountImpl}',
  counter: '${counter}',
  faucetToken: '${faucetToken}',
} as const;
EOF

echo "done: addresses written to $OUTPUT (chain ID: $CHAIN_ID)"
