/**
 * Centralised environment configuration for contract addresses and Pimlico.
 *
 * Contract addresses are resolved from (in order):
 *   1. $env/dynamic/public — lets operators override per environment.
 *   2. `./contracts/addresses.ts` — generated by `scripts/export-addresses.sh`
 *      and committed with the current Sepolia deployment, so fresh clones work
 *      without any PUBLIC_*_ADDRESS env vars.
 *
 * The Pimlico API key has no default and must come from the env.
 */

import { env } from '$env/dynamic/public';
import { isAddress } from 'viem';

import { addresses as generatedAddresses } from './contracts/addresses';

function resolveAddress(envName: string, fallback: string): `0x${string}` {
	const raw = env[envName] ?? fallback;
	if (!raw) throw new Error(`${envName} is not set and no fallback is available`);
	if (!isAddress(raw)) throw new Error(`${envName} is not a valid address: ${raw}`);
	return raw;
}

function requireString(name: string): string {
	const val = env[name];
	if (!val) throw new Error(`${name} is not set`);
	return val;
}

/** SmartAccountFactory deployment address. */
export function factoryAddress(): `0x${string}` {
	return resolveAddress('PUBLIC_FACTORY_ADDRESS', generatedAddresses.factory);
}

/** Counter contract address. */
export function counterAddress(): `0x${string}` {
	return resolveAddress('PUBLIC_COUNTER_ADDRESS', generatedAddresses.counter);
}

/** FaucetToken (BFT) contract address. */
export function faucetTokenAddress(): `0x${string}` {
	return resolveAddress('PUBLIC_FAUCET_TOKEN_ADDRESS', generatedAddresses.faucetToken);
}

/** Pimlico bundler/paymaster RPC URL for Sepolia. */
export function pimlicoUrl(): string {
	const key = requireString('PUBLIC_PIMLICO_API_KEY');
	return `https://api.pimlico.io/v2/sepolia/rpc?apikey=${encodeURIComponent(key)}`;
}
